server:
  port: 9001

spring:
  application:
    name: script_platform

  datasource:
    url: jdbc:mysql://localhost:3306/script_platform?useUnicode=true&characterEncoding=utf-8&isSSL=false
    username: root
    password: root

  jpa:
    show-sql: true
    generate-ddl: false

logging:
  level:
    org.springframework.security: trace
