server:
  port: 9999

spring:
  application:
    name: script_platform

  datasource:
    url: jdbc:mysql://localhost:3306/script_platform?useUnicode=true&characterEncoding=utf-8&isSSL=false
    username: root
    password: root
