### page
GET {{endpoint}}/role/page
Authorization: {{accessToken}}


### create
POST {{endpoint}}/role/create
Authorization: {{accessToken}}
Content-Type: application/json

{
  "name": "资本家4",
  "remark": "the very important person in the platform"
}
