### create
POST {{endpoint}}/user/create
Authorization: {{accessToken}}
Content-Type: application/json

{
  "name": "super_jinx",
  "username": "88888888",
  "password": "88888888",
  "roleIds": [
    1
  ]
}

### profile
GET {{endpoint}}/user/profile
Authorization: {{accessToken}}
